"""Static information and general utility functions for pypsa_validation_processing."""

EU27_COUNTRY_CODES: dict[str, str] = {
    "AL": "Albania",
    "AT": "Austria",
    "AT11": "Burgenland",
    "AT12": "Lower Austria",
    "AT13": "Vienna",
    "AT21": "Carinthia",
    "AT22": "Styria",
    "AT31": "Upper Austria",
    "AT32": "Salzburg",
    "AT33": "Tyrol",
    "AT333": "East Tyrol",
    "AT34": "Vorarlberg",
    "BA": "Bosnia and Herzegovina",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "CH": "Switzerland",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DE": "Germany",
    "DE1": "Germany South-West",
    "DE2": "Germany South-East",
    "DE3": "Germany West",
    "DE4": "Germany East",
    "DE5": "Germany North",
    "DK": "Denmark",
    "DK0": "Denmark West",
    "DK1": "Denmark East",
    "EE": "Estonia",
    "ES": "Spain",
    "ES0": "Spain 0",
    "ES1": "Spain-Mallorca",
    "EU": "European Union",
    "FI": "Finland",
    "FR": "France",
    "FR0": "France 0",
    "FR1": "France-Corsica",
    "GB": "United Kingdom",
    "GB0": "United Kingdom",
    "GB1": "United Kingdom-Northern Ireland",
    "GR": "Greece",
    "HR": "Croatia",
    "HU": "Hungary",
    "IE": "Ireland",
    "IT": "Italy",
    "IT0": "Italy 0",
    "IT1": "Italy-Sicily",
    "IT2": "Italy-Sardinia",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "ME": "Montenegro",
    "MK": "North Macedonia",
    "MT": "Malta",
    "NL": "Netherlands",
    "NO": "Norway",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "RS": "Serbia",
    "SE": "Sweden",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "XK": "Kosovo",
    "EU": "European Union",
}

UNITS_MAPPING = {
    "MWh_el": "MWh",
    "MWh_LHV": "MWh",
    "MWh_th": "MWh",
    "t_co2": "t",
    "": "",
}
