name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.66.0

      - name: Run Tests
        run: pixi run pytest tests/ -v --cov=pypsa_validation_processing --cov-report=xml

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
